media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [cover, title]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: cover, label: Cover image, type: image }
      - { name: title, label: Title, type: string, required: true }
      - {
          name: categories,
          label: Categories,
          type: select,
          options: { values: ["opinion", "news", "column"] },
        }
      - { name: author, label: Authors, type: string, list: true }
      - { name: meta, label: Meta, type: string }
      - { name: body, label: Body, type: rich-text }
