url: "https://ekshathe.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ekshathe" # the name of your site, e.g. ACME Corp.
collections:
  pages:
    output: true
    permalink: /:name
  # people:
  #   output: false

plugins:
  - jekyll-seo-tag
  - jekyll-datapage-generator
  - jekyll-spaceship

page_gen-dirs: true

page_gen:
  - data: "casualties"
    template: "person"
    dir: "casualties"
    name: "name"
    index_files: "true"
    title: "name"

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false
