name: Deploy ekshathe
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:
# job 1: publish
# step 1: download and convert csv
# step 2: build
# step 3: deploy

# job 2: upload assets

# job 3: cms

jobs:
  getdata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Node
        working-directory: ./converter
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.x
          cache: npm
      - name: Generate data
        working-directory: ./converter
        run: npm run convert
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build site
        run: jekyll build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: YOUR_ACCOUNT_ID
          projectName: ekshathe
          directory: _sites
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: main
          # Optional: Change the working directory
          # workingDirectory: my-site
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: "3"
